# InfoBoardReborn Config, Last Edited in v2.1.0
# =============================================================================
# |                     Updater: Checks for updates on enable                 |
# |           Debug: Gives extra info on plugin (cmds/startup/errors)         |
# |                  give-onjoin: give a scoreboard onjoin                    |
# |---------------------------------------------------------------------------|
# |       Custom Variables allow for you to create your own variables         |
# |                  <Variable>: What it gets replaced to                     |
# |---------------------------------------------------------------------------|
# |     Disabled Worlds    - A List of worlds that won't have scoreboards     |
# | WorldGuard.Prevent Showing In - A List of regions the board won't show in |
# |---------------------------------------------------------------------------|
# |          Update Time how fast you scoreboard updates in seconds           |
# |---------------------------------------------------------------------------|
# | Scrolling Text is a cool feature where text will scroll across the board  |
# |                Currently format codes aren't supported                    |
# |        Shift Time - How long between the text scrolling in seconds        |
# |---------------------------------------------------------------------------|
# |                             Changeable text:                              |
# |                     Use like: <changeable_<variable>>                     |
# |                       Enabled- enable or disable                          |
# |                  Changeables - Custom changeable variables                |
# |                  Text - the text lines you want to display                |
# |	             interval- how fast the lines should update in seconds        | 
# |---------------------------------------------------------------------------|
# |                                Condition                                  |
# |                      Use like: <condition_<variable>>                     |
# |                         Enabled: enable or disable                        |
# |                   Conditions: Custom condition variables                  |
# |                       Check: variable you check for                       |
# |                  Answer: possible answers on the check                    |
# |             Interval: how fast you want to check in seconds               |
# =============================================================================
Updater: true
Debug: false
give-onjoin: true

Custom Variables:
  <website>: yoursitehere.net
  <plugindev>: Ktar5 & Pixar02

Disabled Worlds:
- DisabledWorld1
- DisabledWorld2

WorldGuard:
  Prevent Showing In:
  - regionNamesAreCapSensitive
  - regionName2

Update Time:
  Lines: 0.5
# Comming soon!
#  Title: 0.5

Scrolling Text:
  Enable: false
  Shift Time: 0.25

Changeable Text:
  Enable: false   
  Changeables:
    healthloc:
      text:
      - '&e%player_health%&a/&c%player_max_health%'
      - '&a%player_x%&7, &a%player_y%&7, &a%player_z%'
      - '&l%player_first_join_date%'
      interval: 1

Condition:
  Enabled: false
  Conditions:
    temp:
      check: "%player_health%"
      answer:
        '20,0': "full health"
        '10,0': "half health"
        '1,0': "close to death"
        '0,0': "dead"
        default: "still alive"
      interval: 1
  