name: InfoBoardReborn
main: com.infogroup.infoboard.InfoBoardReborn
version: 2.0.3
authors: [Ktar5, pixar02]
website : "bit.ly/InfoBoardReborn_spigot & bit.ly/InfoBoardReborn_bukkit" 
description: Show a scoreboard
depend: [PlaceholderAPI, Vault, WorldGuard]
softdepend: [ProtocolLib]

commands:
  InfoBoardReborn:
    usage: /<command> [args]
    description: The main command for this plugin
    aliases: [ibr, ib, iboard, infob, Infoboard]
    
permissions:
  ibr.*:
    default: op
    children:
      ibr.Set: true
      ibr.Toggle: true
      ibr.Reload: true
      ibr.View: true
      ibr.Create: true
  ibr.View:
    default: true
  ibr.Toggle:
    default: true
  
